#pragma once

#import <Foundation/Foundation.h>
#include <string>

// Two-language UI strings (English / Simplified Chinese), toggled at runtime.
enum class Lang { english, chinese };

// Message keys — one per user-visible string.
enum class Str {
    open_songs,
    open_songs_accessibility,
    no_song_selected,
    open_to_begin,
    open_formats,
    open_button_help,
    open_no_compatible,
    lyre,
    songs_suffix,       // "songs" as in "12 songs"
    playing,
    paused,
    idle,
    no_song,
    counting_in,
    starting_in,        // "starting in %lld…" — caller appends
    // tooltips
    tip_collapse,
    tip_close,
    tip_add,
    tip_settings,
    tip_previous,
    tip_loop,
    tip_playpause,
    tip_stop,
    tip_next,
    tip_speed,
    tip_playlist,
    // menu
    menu_autopause,
    menu_reset_speed,
    menu_practice,
    menu_playback,
    menu_play_background,
    menu_accessibility,
    menu_learn,
    menu_tempo_practice,
    menu_auto_speed,
    menu_lock_mastered,
    menu_restart_phrase,
    menu_practice_insights,
    menu_show_upcoming,
    menu_count_in,
    menu_latency_offset,
    menu_metronome,
    menu_high_contrast,
    menu_reduced_motion,
    menu_queue_move_up,
    menu_queue_move_down,
    menu_queue_remove,
    menu_queue_clear,
    menu_queue_favorite,
    menu_queue_unfavorite,
    menu_recent,
    menu_favorites_only,
    menu_no_favorites,
    mode_practice,
    mode_automatic,
    menu_safety,
    menu_theme,
    menu_language,
    menu_lang_english,
    menu_lang_chinese,
    // open panel
    panel_message,
    panel_add,
    panel_ok,
    learn_ready,
    learn_note,
    learn_complete,
    learn_wrong,
    learn_partial,
    learn_early,
    learn_late,
    learn_missed,
    learn_now,
    learn_next,
    dashboard_title,
    dashboard_no_data,
    dashboard_accuracy,
    dashboard_notes,
    dashboard_wrong,
    dashboard_partials,
    dashboard_chords,
    dashboard_response,
    dashboard_phrases,
    dashboard_mastered,
    dashboard_phrase,
    dashboard_best,
    dashboard_focus,
    dashboard_grade,
    dashboard_timing,
    dashboard_on_time,
    dashboard_timing_hint,
    dashboard_clean_runs,
    dashboard_new_best,
    dashboard_vs_best,
    dashboard_phrases_mastered,
    dashboard_legend_session,
    dashboard_legend_best,
    dashboard_first_session,
    option_off,
    seconds_format,
    ramp_from_current,
    ramp_from_percent,
    menu_difficulty,
    difficulty_easy,
    difficulty_normal,
    difficulty_strict,
    menu_show_summary,
    learn_streak,
    dashboard_streak,
    dashboard_best_streak,
    dashboard_rushing,
    dashboard_dragging,
    dashboard_steady,
    dashboard_progress,
    dashboard_progress_hint,
    dashboard_sessions_count,
    summary_title,
    summary_weakest,
    learn_phrase_of,
    metronome_note_cues,
    metronome_steady,
    metronome_steady_bpm,
    menu_drill,
    menu_stop_drill,
    drill_status,
    drill_none,
    drill_done,
    dashboard_chart_hint,
    dashboard_looping,
    menu_note_highway,
    highway_title,
    highway_empty,
    menu_key_overlay,
    menu_key_overlay_unset,
    menu_key_preview,
    menu_key_section,
    menu_appearance,
    menu_calibrate,
    menu_reset_calibration,
    calib_status_custom,
    calib_status_default,
    calib_need_genshin,
    calib_done,
    calib_step_q,
    calib_step_m,
    calib_review,
    calib_hint_keys,
    calib_hint_cancel,
    calib_save,
    calib_redo,
    calib_cancel,
    menu_adjust_keys,
    calib_adjust,
    calib_hint_adjust,
    settings_title,
    library_title,
    library_all,
    library_favorites,
    library_search,
    library_empty,
    library_no_match,
    library_sources,    // "%ld sources" — format argument
    library_now_playing,
    library_tip_open,
};

namespace strings {

Lang current();
void set_current(Lang lang);

// Localized string for a key.
NSString* get(Str key);

}  // namespace strings
