#include "strings.h"

#include <unordered_map>

namespace strings {
namespace {

Lang g_lang = Lang::english;

const std::unordered_map<Str, NSString*>& table_en() {
    static const std::unordered_map<Str, NSString*> t = {
        {Str::open_songs,       @"Open songs…"},
        {Str::open_songs_accessibility, @"Open songs"},
        {Str::no_song_selected, @"No song selected"},
        {Str::open_to_begin,    @"Choose a song to begin"},
        {Str::open_formats,     @"Choose a song file or folder"},
        {Str::open_button_help, @"Choose a .genshinsheet, .mid, or .midi file, or a folder"},
        {Str::open_no_compatible, @"No compatible songs found"},
        {Str::lyre,             @"Lyre"},
        {Str::songs_suffix,     @"songs"},
        {Str::playing,          @"playing"},
        {Str::paused,           @"paused"},
        {Str::idle,             @"idle"},
        {Str::no_song,          @"no song"},
        {Str::counting_in,      @"counting in"},
        {Str::starting_in,      @"starting in"},
        {Str::tip_collapse,     @"Collapse / expand"},
        {Str::tip_close,        @"Close and quit"},
        {Str::tip_add,          @"Add songs"},
        {Str::tip_settings,     @"Settings"},
        {Str::tip_previous,     @"Previous"},
        {Str::tip_loop,         @"Loop"},
        {Str::tip_playpause,    @"Play / Pause"},
        {Str::tip_stop,         @"Stop"},
        {Str::tip_next,         @"Next"},
        {Str::tip_speed,        @"Playback speed — click to cycle, scroll to fine-tune"},
        {Str::tip_playlist,     @"Playlist"},
        {Str::menu_autopause,   @"Auto-pause when Genshin loses focus"},
        {Str::menu_reset_speed, @"Reset speed to 1×"},
        {Str::menu_practice,    @"Practice"},
        {Str::menu_playback,    @"Playback"},
        {Str::menu_play_background, @"Play in Background"},
        {Str::menu_accessibility, @"Accessibility"},
        {Str::menu_learn,       @"Learn mode"},
        {Str::menu_tempo_practice, @"Practice at song speed"},
        {Str::menu_auto_speed,  @"Gradual speed-up"},
        {Str::menu_lock_mastered, @"Loop phrase until mastered"},
        {Str::menu_restart_phrase, @"Restart phrase"},
        {Str::menu_practice_insights, @"Practice insights…"},
        {Str::menu_show_upcoming, @"Show upcoming note"},
        {Str::menu_count_in,     @"Count-in"},
        {Str::menu_latency_offset, @"Practice timing offset"},
        {Str::menu_metronome,   @"Metronome"},
        {Str::menu_high_contrast, @"High contrast"},
        {Str::menu_reduced_motion, @"Reduce motion"},
        {Str::menu_queue_move_up, @"Move current up"},
        {Str::menu_queue_move_down, @"Move current down"},
        {Str::menu_queue_remove, @"Remove from queue"},
        {Str::menu_queue_clear,  @"Clear queue"},
        {Str::menu_queue_favorite, @"Add to favorites"},
        {Str::menu_queue_unfavorite, @"Remove from favorites"},
        {Str::menu_recent,       @"Recently played"},
        {Str::menu_favorites_only, @"Show favorites only"},
        {Str::menu_no_favorites, @"No favorites yet"},
        {Str::mode_practice,     @"Learn"},
        {Str::mode_automatic,    @"Auto"},
        {Str::menu_safety,       @"Manual practice sends no automated keystrokes"},
        {Str::menu_theme,       @"Theme"},
        {Str::menu_language,    @"Language"},
        {Str::menu_lang_english,@"English"},
        {Str::menu_lang_chinese,@"中文"},
        {Str::panel_message,    @"Choose .genshinsheet or .mid/.midi files or folders"},
        {Str::panel_add,        @"Add"},
        {Str::panel_ok,         @"OK"},
        {Str::learn_ready,      @"Learn mode — press play to begin"},
        {Str::learn_note,       @"Play together: %@"},
        {Str::learn_complete,   @"Song learned — press play to try again"},
        {Str::learn_wrong,      @"Wrong key"},
        {Str::learn_partial,    @"Chord partial"},
        {Str::learn_early,      @"Early"},
        {Str::learn_late,       @"Late"},
        {Str::learn_missed,     @"Missed"},
        {Str::learn_now,        @"Now"},
        {Str::learn_next,       @"Next"},
        {Str::dashboard_title,  @"Practice Insights"},
        {Str::dashboard_no_data, @"Play a few notes to see your progress"},
        {Str::dashboard_accuracy, @"Accuracy"},
        {Str::dashboard_notes,  @"Notes"},
        {Str::dashboard_wrong,  @"Wrong keys"},
        {Str::dashboard_partials, @"Partial chords"},
        {Str::dashboard_chords, @"Chords"},
        {Str::dashboard_response, @"Avg response"},
        {Str::dashboard_phrases, @"Phrase accuracy"},
        {Str::dashboard_mastered, @"Mastered"},
        {Str::dashboard_phrase,  @"Phrase %lu"},
        {Str::dashboard_best,    @"Best"},
        {Str::dashboard_focus,   @"Focus"},
        {Str::dashboard_grade,   @"Grade"},
        {Str::dashboard_timing,  @"Timing"},
        {Str::dashboard_on_time, @"On time"},
        {Str::dashboard_timing_hint, @"Turn on “Practice at song speed” to track timing"},
        {Str::dashboard_clean_runs, @"Clean runs"},
        {Str::dashboard_new_best, @"New best"},
        {Str::dashboard_vs_best, @"%@ vs best %@"},
        {Str::dashboard_phrases_mastered, @"%lu of %lu phrases mastered"},
        {Str::dashboard_legend_session, @"This session"},
        {Str::dashboard_legend_best, @"Best"},
        {Str::dashboard_first_session, @"First session — set your baseline"},
        {Str::option_off, @"Off"},
        {Str::seconds_format, @"%ld seconds"},
        {Str::ramp_from_current, @"From current speed"},
        {Str::ramp_from_percent, @"Start at %ld%%"},
        {Str::menu_difficulty, @"Timing difficulty"},
        {Str::difficulty_easy, @"Easy"},
        {Str::difficulty_normal, @"Normal"},
        {Str::difficulty_strict, @"Strict"},
        {Str::menu_show_summary, @"Show summary after practice"},
        {Str::learn_streak, @"%lu streak"},
        {Str::dashboard_streak, @"Streak"},
        {Str::dashboard_best_streak, @"Best streak %lu"},
        {Str::dashboard_rushing, @"Rushing %ld ms"},
        {Str::dashboard_dragging, @"Dragging %ld ms"},
        {Str::dashboard_steady, @"On the beat (±%ld ms)"},
        {Str::dashboard_progress, @"Progress"},
        {Str::dashboard_progress_hint, @"Finish a session to start your progress chart"},
        {Str::dashboard_sessions_count, @"Last %lu sessions"},
        {Str::summary_title, @"Session complete"},
        {Str::summary_weakest, @"Weakest: %@"},
        {Str::learn_phrase_of, @"Phrase %lu/%lu"},
        {Str::metronome_note_cues, @"Note cues"},
        {Str::metronome_steady, @"Steady beat"},
        {Str::metronome_steady_bpm, @"Steady beat (%ld BPM)"},
        {Str::menu_drill, @"Drill weakest phrases"},
        {Str::menu_stop_drill, @"Stop drill"},
        {Str::drill_status, @"Drill %lu/%lu"},
        {Str::drill_none, @"No weak phrases yet — practice a few songs first"},
        {Str::drill_done, @"Drill complete — every phrase mastered"},
        {Str::dashboard_chart_hint, @"Click a phrase to loop it · click again to release"},
        {Str::dashboard_looping, @"Looping %@"},
    };
    return t;
}

const std::unordered_map<Str, NSString*>& table_zh() {
    static const std::unordered_map<Str, NSString*> t = {
        {Str::open_songs,       @"打开乐谱…"},
        {Str::open_songs_accessibility, @"打开乐谱"},
        {Str::no_song_selected, @"未选择乐曲"},
        {Str::open_to_begin,    @"选择乐谱以开始"},
        {Str::open_formats,     @"选择乐谱文件或文件夹"},
        {Str::open_button_help, @"选择 .genshinsheet、.mid 或 .midi 文件，也可以选择文件夹"},
        {Str::open_no_compatible, @"没有找到兼容的乐谱"},
        {Str::lyre,             @"风物之诗琴"},
        {Str::songs_suffix,     @"首"},
        {Str::playing,          @"播放中"},
        {Str::paused,           @"已暂停"},
        {Str::idle,             @"空闲"},
        {Str::no_song,          @"无乐曲"},
        {Str::counting_in,      @"准备中"},
        {Str::starting_in,      @"倒计时"},
        {Str::tip_collapse,     @"折叠 / 展开"},
        {Str::tip_close,        @"关闭并退出"},
        {Str::tip_add,          @"添加乐曲"},
        {Str::tip_settings,     @"设置"},
        {Str::tip_previous,     @"上一首"},
        {Str::tip_loop,         @"循环"},
        {Str::tip_playpause,    @"播放 / 暂停"},
        {Str::tip_stop,         @"停止"},
        {Str::tip_next,         @"下一首"},
        {Str::tip_speed,        @"播放速度 — 点击切换，滚动微调"},
        {Str::tip_playlist,     @"播放列表"},
        {Str::menu_autopause,   @"原神失去焦点时自动暂停"},
        {Str::menu_reset_speed, @"重置速度为 1×"},
        {Str::menu_practice,    @"练习"},
        {Str::menu_playback,    @"播放"},
        {Str::menu_play_background, @"后台播放"},
        {Str::menu_accessibility, @"辅助功能"},
        {Str::menu_learn,       @"练习模式"},
        {Str::menu_tempo_practice, @"按歌曲速度练习"},
        {Str::menu_auto_speed,  @"逐步加速"},
        {Str::menu_lock_mastered, @"循环练习乐句直到掌握"},
        {Str::menu_restart_phrase, @"重新练习乐句"},
        {Str::menu_practice_insights, @"练习数据…"},
        {Str::menu_show_upcoming, @"显示下一个音符"},
        {Str::menu_count_in,     @"预备拍"},
        {Str::menu_latency_offset, @"练习延迟校准"},
        {Str::menu_metronome,   @"节拍器"},
        {Str::menu_high_contrast, @"高对比度"},
        {Str::menu_reduced_motion, @"减少动态效果"},
        {Str::menu_queue_move_up, @"上移当前乐曲"},
        {Str::menu_queue_move_down, @"下移当前乐曲"},
        {Str::menu_queue_remove, @"从队列移除"},
        {Str::menu_queue_clear,  @"清空队列"},
        {Str::menu_queue_favorite, @"加入收藏"},
        {Str::menu_queue_unfavorite, @"取消收藏"},
        {Str::menu_recent,       @"最近播放"},
        {Str::menu_favorites_only, @"仅显示收藏"},
        {Str::menu_no_favorites, @"还没有收藏"},
        {Str::mode_practice,     @"练习"},
        {Str::mode_automatic,    @"自动"},
        {Str::menu_safety,       @"手动练习不会自动发送按键"},
        {Str::menu_theme,       @"主题"},
        {Str::menu_language,    @"语言"},
        {Str::menu_lang_english,@"English"},
        {Str::menu_lang_chinese,@"中文"},
        {Str::panel_message,    @"选择 .genshinsheet 或 .mid/.midi 文件或文件夹"},
        {Str::panel_add,        @"添加"},
        {Str::panel_ok,         @"好"},
        {Str::learn_ready,      @"练习模式 — 点击播放开始"},
        {Str::learn_note,       @"同时演奏 %@"},
        {Str::learn_complete,   @"已完成练习 — 点击播放再来一次"},
        {Str::learn_wrong,      @"错键"},
        {Str::learn_partial,    @"和弦未完成"},
        {Str::learn_early,      @"太早"},
        {Str::learn_late,       @"太晚"},
        {Str::learn_missed,     @"漏弹"},
        {Str::learn_now,        @"当前"},
        {Str::learn_next,       @"下一个"},
        {Str::dashboard_title,  @"练习数据"},
        {Str::dashboard_no_data, @"演奏几组音符后即可查看进度"},
        {Str::dashboard_accuracy, @"准确率"},
        {Str::dashboard_notes,  @"音符"},
        {Str::dashboard_wrong,  @"错键"},
        {Str::dashboard_partials, @"未完成和弦"},
        {Str::dashboard_chords, @"和弦"},
        {Str::dashboard_response, @"平均反应"},
        {Str::dashboard_phrases, @"乐句准确率"},
        {Str::dashboard_mastered, @"已掌握"},
        {Str::dashboard_phrase,  @"乐句 %lu"},
        {Str::dashboard_best,    @"最佳"},
        {Str::dashboard_focus,   @"重点"},
        {Str::dashboard_grade,   @"评级"},
        {Str::dashboard_timing,  @"节奏"},
        {Str::dashboard_on_time, @"准时"},
        {Str::dashboard_timing_hint, @"开启“按歌曲速度练习”以记录节奏"},
        {Str::dashboard_clean_runs, @"无错连续"},
        {Str::dashboard_new_best, @"新纪录"},
        {Str::dashboard_vs_best, @"%@ 对比最佳 %@"},
        {Str::dashboard_phrases_mastered, @"已掌握 %lu / %lu 个乐句"},
        {Str::dashboard_legend_session, @"本次练习"},
        {Str::dashboard_legend_best, @"最佳"},
        {Str::dashboard_first_session, @"首次练习 — 建立基准"},
        {Str::option_off, @"关闭"},
        {Str::seconds_format, @"%ld 秒"},
        {Str::ramp_from_current, @"从当前速度开始"},
        {Str::ramp_from_percent, @"从 %ld%% 开始"},
        {Str::menu_difficulty, @"节奏难度"},
        {Str::difficulty_easy, @"简单"},
        {Str::difficulty_normal, @"普通"},
        {Str::difficulty_strict, @"严格"},
        {Str::menu_show_summary, @"练习结束后显示总结"},
        {Str::learn_streak, @"连击 %lu"},
        {Str::dashboard_streak, @"连击"},
        {Str::dashboard_best_streak, @"最高连击 %lu"},
        {Str::dashboard_rushing, @"偏快 %ld 毫秒"},
        {Str::dashboard_dragging, @"偏慢 %ld 毫秒"},
        {Str::dashboard_steady, @"节奏稳定（±%ld 毫秒）"},
        {Str::dashboard_progress, @"进步曲线"},
        {Str::dashboard_progress_hint, @"完成一次练习后即可查看进步曲线"},
        {Str::dashboard_sessions_count, @"最近 %lu 次练习"},
        {Str::summary_title, @"练习完成"},
        {Str::summary_weakest, @"最薄弱：%@"},
        {Str::learn_phrase_of, @"乐句 %lu/%lu"},
        {Str::metronome_note_cues, @"音符提示"},
        {Str::metronome_steady, @"稳定节拍"},
        {Str::metronome_steady_bpm, @"稳定节拍（%ld BPM）"},
        {Str::menu_drill, @"练习最薄弱的乐句"},
        {Str::menu_stop_drill, @"停止专项练习"},
        {Str::drill_status, @"专项 %lu/%lu"},
        {Str::drill_none, @"还没有薄弱乐句 — 先练习几首乐曲吧"},
        {Str::drill_done, @"专项练习完成 — 所有乐句均已掌握"},
        {Str::dashboard_chart_hint, @"点击乐句可循环练习 · 再次点击取消"},
        {Str::dashboard_looping, @"循环中：%@"},
    };
    return t;
}

}  // namespace

Lang current() { return g_lang; }
void set_current(Lang lang) { g_lang = lang; }

NSString* get(Str key) {
    const auto& t = (g_lang == Lang::chinese) ? table_zh() : table_en();
    const auto it = t.find(key);
    return it != t.end() ? it->second : @"";
}

}  // namespace strings
